# Generated by Django 5.1.7 on 2025-04-23 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('birim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255, verbose_name='Bölüm Adı')),
                ('birim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolumler', to='birim.birim')),
            ],
            options={
                'verbose_name': 'Bölüm',
                'verbose_name_plural': 'Bölümler',
            },
        ),
    ]
