# Generated by Django 5.1.7 on 2025-04-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BelgeSablonu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('TABLO5', 'Tablo 5 Şablonu'), ('JURI_RAPORU', 'Jüri Rapor Şablonu'), ('KARAR_RAPORU', 'Karar Rapor Şablonu'), ('BASVURU_FORMU', 'Başvuru Formu')], max_length=15, verbose_name='Şablon Türü')),
                ('baslik', models.CharField(max_length=255, verbose_name='Şablon Başlığı')),
                ('icerik', models.TextField(verbose_name='Şablon İçeriği')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Belge Şablonu',
                'verbose_name_plural': 'Belge Şablonları',
            },
        ),
    ]
