# Generated by Django 5.1.7 on 2025-04-23 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kadro_tipi', '0001_initial'),
        ('temel_alan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtamaKriteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_makale_sayisi', models.IntegerField(verbose_name='Minimum Makale Sayısı')),
                ('min_baslica_yazar', models.IntegerField(verbose_name='Minimum Başlıca Yazar Sayısı')),
                ('min_a1_a2_makale', models.IntegerField(default=0, verbose_name='Min A1-A2 Makale')),
                ('min_a1_a4_makale', models.IntegerField(default=0, verbose_name='Min A1-A4 Makale')),
                ('min_a1_a5_makale', models.IntegerField(default=0, verbose_name='Min A1-A5 Makale')),
                ('min_a1_a6_makale', models.IntegerField(default=0, verbose_name='Min A1-A6 Makale')),
                ('min_a1_a8_makale', models.IntegerField(default=0, verbose_name='Min A1-A8 Makale')),
                ('min_kisisel_etkinlik', models.IntegerField(default=0, verbose_name='Min Kişisel Etkinlik')),
                ('min_karma_etkinlik', models.IntegerField(default=0, verbose_name='Min Karma Etkinlik')),
                ('min_tez_danismanligi', models.IntegerField(default=0, verbose_name='Min Tez Danışmanlığı')),
                ('min_toplam_puan', models.IntegerField(verbose_name='Minimum Toplam Puan')),
                ('kadro_tipi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atama_kriterleri', to='kadro_tipi.kadrotipi')),
                ('temel_alan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atama_kriterleri', to='temel_alan.temelalan')),
            ],
            options={
                'verbose_name': 'Atama Kriteri',
                'verbose_name_plural': 'Atama Kriterleri',
                'unique_together': {('temel_alan', 'kadro_tipi')},
            },
        ),
    ]
