# Generated by Django 5.1.7 on 2025-04-23 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basvuru', '0003_initial'),
        ('juri', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='juriatama',
            name='juri_uyesi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juri_gorevleri', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='juridegerlendirme',
            name='basvuru',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juri_degerlendirmeleri', to='basvuru.basvuru'),
        ),
        migrations.AddField(
            model_name='juridegerlendirme',
            name='juri_atama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degerlendirmeler', to='juri.juriatama'),
        ),
        migrations.AlterUniqueTogether(
            name='juriatama',
            unique_together={('ilan', 'juri_uyesi')},
        ),
        migrations.AlterUniqueTogether(
            name='juridegerlendirme',
            unique_together={('juri_atama', 'basvuru')},
        ),
    ]
