# Generated by Django 5.1.7 on 2025-04-27 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0002_initial'),
        ('juri', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='juriatama',
            options={'verbose_name': 'Jüri Ataması', 'verbose_name_plural': 'Jüri Atamaları'},
        ),
        migrations.AlterModelOptions(
            name='juridegerlendirme',
            options={'verbose_name': 'Jüri Değerlendirmesi', 'verbose_name_plural': 'Jüri Değerlendirmeleri'},
        ),
        migrations.AlterUniqueTogether(
            name='juriatama',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='juriatama',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='juridegerlendirme',
            name='guncelleme_tarihi',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='juriatama',
            name='juri_uyesi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juri_atamalari', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='juridegerlendirme',
            name='aciklama',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='juridegerlendirme',
            name='rapor',
            field=models.FileField(blank=True, null=True, upload_to='juri_raporlari/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='juridegerlendirme',
            name='sonuc',
            field=models.CharField(choices=[('OLUMLU', 'Olumlu'), ('OLUMSUZ', 'Olumsuz')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='juriatama',
            unique_together={('juri_uyesi', 'ilan')},
        ),
    ]
