# Generated by Django 5.1.7 on 2025-04-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bildirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255, verbose_name='Bildirim Başlığı')),
                ('mesaj', models.TextField(verbose_name='Bildirim Mesajı')),
                ('tur', models.CharField(choices=[('BASVURU', 'Başvuru Bildirimi'), ('JURI', 'Jüri Bildirimi'), ('DEGERLENDIRME', 'Değerlendirme Bildirimi'), ('SONUC', 'Sonuç Bildirimi'), ('SISTEM', 'Sistem Bildirimi')], max_length=15, verbose_name='Bildirim Türü')),
                ('okundu', models.BooleanField(default=False, verbose_name='Okundu mu?')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
            },
        ),
    ]
