# Generated by Django 5.1.7 on 2025-04-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KadroTipi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('DR_OGR_UYESI', 'Dr. Öğretim Üyesi'), ('DOCENT', 'Doçent'), ('PROFESOR', 'Profesör')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Kadro Tipi',
                'verbose_name_plural': 'Kadro Tipleri',
            },
        ),
    ]
