# Generated by Django 5.1.7 on 2025-04-23 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anabilim_dali', '0001_initial'),
        ('birim', '0001_initial'),
        ('bolum', '0001_initial'),
        ('kadro_tipi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255, verbose_name='İlan Başlığı')),
                ('aciklama', models.TextField(verbose_name='İlan Açıklaması')),
                ('baslangic_tarihi', models.DateTimeField(verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateTimeField(verbose_name='Bitiş Tarihi')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('anabilim_dali', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilanlar', to='anabilim_dali.anabilimdali')),
                ('birim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilanlar', to='birim.birim')),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilanlar', to='bolum.bolum')),
                ('kadro_tipi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilanlar', to='kadro_tipi.kadrotipi')),
            ],
            options={
                'verbose_name': 'İlan',
                'verbose_name_plural': 'İlanlar',
            },
        ),
    ]
