# Generated by Django 5.1.7 on 2025-04-23 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basvuru', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaaliyetKategorisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=5, verbose_name='Kategori Kodu')),
                ('baslik', models.CharField(max_length=255, verbose_name='Kategori Başlığı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Faaliyet Kategorisi',
                'verbose_name_plural': 'Faaliyet Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='AtifDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atif_yapilan_eser', models.CharField(max_length=255, verbose_name='Atıf Yapılan Eser')),
                ('atif_yapan_eser', models.CharField(max_length=255, verbose_name='Atıf Yapan Eser')),
                ('atif_yili', models.IntegerField(verbose_name='Atıf Yılı')),
                ('atif_indeksi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Atıf İndeksi')),
                ('aday_faaliyet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atif_detay', to='basvuru.adayfaaliyet')),
            ],
            options={
                'verbose_name': 'Atıf Detay',
                'verbose_name_plural': 'Atıf Detayları',
            },
        ),
        migrations.CreateModel(
            name='KitapDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yayinevi', models.CharField(max_length=255, verbose_name='Yayınevi')),
                ('isbn', models.CharField(max_length=20, verbose_name='ISBN')),
                ('basim_yili', models.IntegerField(verbose_name='Basım Yılı')),
                ('uluslararasi_mi', models.BooleanField(default=False, verbose_name='Uluslararası mı?')),
                ('aday_faaliyet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kitap_detay', to='basvuru.adayfaaliyet')),
            ],
            options={
                'verbose_name': 'Kitap Detay',
                'verbose_name_plural': 'Kitap Detayları',
            },
        ),
        migrations.CreateModel(
            name='MakaleDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dergi_adi', models.CharField(max_length=255, verbose_name='Dergi Adı')),
                ('cilt_no', models.CharField(max_length=50, verbose_name='Cilt No')),
                ('sayfa', models.CharField(max_length=50, verbose_name='Sayfa')),
                ('yil', models.IntegerField(verbose_name='Yıl')),
                ('doi', models.CharField(blank=True, max_length=255, null=True, verbose_name='DOI')),
                ('indeks', models.CharField(blank=True, max_length=50, null=True, verbose_name='İndeks')),
                ('q_dilimi', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4'), ('NONE', 'Yok')], default='NONE', max_length=4, verbose_name='Q Dilimi')),
                ('derleme_mi', models.BooleanField(default=False, verbose_name='Derleme Makalesi mi?')),
                ('aday_faaliyet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='makale_detay', to='basvuru.adayfaaliyet')),
            ],
            options={
                'verbose_name': 'Makale Detay',
                'verbose_name_plural': 'Makale Detayları',
            },
        ),
        migrations.CreateModel(
            name='ProjeDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proje_turu', models.CharField(choices=[('AB', 'AB Çerçeve'), ('TUBITAK', 'TÜBİTAK'), ('KALKINMA_AJANSI', 'Kalkınma Ajansı'), ('SANAYI', 'Sanayi'), ('BAP', 'BAP'), ('DIGER', 'Diğer')], max_length=20, verbose_name='Proje Türü')),
                ('proje_rolu', models.CharField(choices=[('KOORDINATOR', 'Koordinatör'), ('YURUTUCU', 'Yürütücü'), ('ARASTIRMACI', 'Araştırmacı'), ('DANISMAN', 'Danışman')], max_length=15, verbose_name='Proje Rolü')),
                ('proje_butcesi', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Proje Bütçesi')),
                ('baslangic_tarihi', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('destekleyen_kurulus', models.CharField(max_length=255, verbose_name='Destekleyen Kuruluş')),
                ('aday_faaliyet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proje_detay', to='basvuru.adayfaaliyet')),
            ],
            options={
                'verbose_name': 'Proje Detay',
                'verbose_name_plural': 'Proje Detayları',
            },
        ),
        migrations.CreateModel(
            name='SanatsalFaaliyetDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etkinlik_turu', models.CharField(choices=[('KISISEL', 'Kişisel'), ('KARMA', 'Karma'), ('RESITAL', 'Resital'), ('KONSER', 'Konser'), ('DIGER', 'Diğer')], max_length=10, verbose_name='Etkinlik Türü')),
                ('etkinlik_yeri', models.CharField(max_length=255, verbose_name='Etkinlik Yeri')),
                ('etkinlik_tarihi', models.DateField(verbose_name='Etkinlik Tarihi')),
                ('uluslararasi_mi', models.BooleanField(default=False, verbose_name='Uluslararası mı?')),
                ('aday_faaliyet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sanatsal_faaliyet_detay', to='basvuru.adayfaaliyet')),
            ],
            options={
                'verbose_name': 'Sanatsal Faaliyet Detay',
                'verbose_name_plural': 'Sanatsal Faaliyet Detayları',
            },
        ),
        migrations.CreateModel(
            name='TezDanismanligiDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogrenci_adi', models.CharField(max_length=255, verbose_name='Öğrenci Adı')),
                ('tez_konusu', models.CharField(max_length=255, verbose_name='Tez Konusu')),
                ('tez_turu', models.CharField(choices=[('YUKSEK_LISANS', 'Yüksek Lisans'), ('DOKTORA', 'Doktora/Sanatta Yeterlik'), ('TIP_DIS_UZMANLIK', 'Tıp/Diş Uzmanlık')], max_length=20, verbose_name='Tez Türü')),
                ('tamamlanma_tarihi', models.DateField(verbose_name='Tamamlanma Tarihi')),
                ('es_danisman_mi', models.BooleanField(default=False, verbose_name='Eş Danışman mı?')),
                ('aday_faaliyet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tez_danismanligi_detay', to='basvuru.adayfaaliyet')),
            ],
            options={
                'verbose_name': 'Tez Danışmanlığı Detay',
                'verbose_name_plural': 'Tez Danışmanlığı Detayları',
            },
        ),
        migrations.CreateModel(
            name='Faaliyet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=10, verbose_name='Faaliyet Kodu')),
                ('baslik', models.CharField(max_length=255, verbose_name='Faaliyet Başlığı')),
                ('puan', models.IntegerField(verbose_name='Puan Değeri')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faaliyetler', to='faaliyet.faaliyetkategorisi')),
            ],
            options={
                'verbose_name': 'Faaliyet',
                'verbose_name_plural': 'Faaliyetler',
                'unique_together': {('kategori', 'kod')},
            },
        ),
    ]
