# Generated by Django 5.1.7 on 2025-04-23 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bolum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnabilimDali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255, verbose_name='Anabilim Dalı Adı')),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anabilim_dallari', to='bolum.bolum')),
            ],
            options={
                'verbose_name': 'Anabilim Dalı',
                'verbose_name_plural': 'Anabilim Dalları',
            },
        ),
    ]
