# Generated by Django 5.1.7 on 2025-04-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdayFaaliyet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255, verbose_name='Faaliyet Başlığı')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('yazar_sayisi', models.IntegerField(default=1, verbose_name='Yazar Sayısı')),
                ('baslica_yazar_mi', models.BooleanField(default=False, verbose_name='Başlıca Yazar mı?')),
                ('kisi_puani', models.FloatField(blank=True, null=True, verbose_name='Kişi Puanı')),
                ('kanit_belgesi', models.FileField(upload_to='kanitlar/', verbose_name='Kanıt Belgesi')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aday Faaliyet',
                'verbose_name_plural': 'Aday Faaliyetler',
            },
        ),
        migrations.CreateModel(
            name='Basvuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(choices=[('BEKLEMEDE', 'Beklemede'), ('INCELEMEDE', 'İncelemede'), ('ONAYLANDI', 'Onaylandı'), ('REDDEDILDI', 'Reddedildi')], default='BEKLEMEDE', max_length=15)),
                ('basvuru_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('ozgecmis_dosyasi', models.FileField(upload_to='ozgecmisler/', verbose_name='Özgeçmiş Dosyası')),
                ('diplama_belgeleri', models.FileField(upload_to='diplomalar/', verbose_name='Diploma Belgeleri')),
                ('yabanci_dil_belgesi', models.FileField(upload_to='yabanci_dil/', verbose_name='Yabancı Dil Belgesi')),
            ],
            options={
                'verbose_name': 'Başvuru',
                'verbose_name_plural': 'Başvurular',
            },
        ),
        migrations.CreateModel(
            name='BasvuruSonuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karar', models.CharField(choices=[('BEKLEMEDE', 'Beklemede'), ('INCELEMEDE', 'İncelemede'), ('ONAYLANDI', 'Onaylandı'), ('REDDEDILDI', 'Reddedildi')], max_length=15, verbose_name='Karar')),
                ('karar_tarihi', models.DateTimeField(auto_now_add=True)),
                ('karar_raporu', models.FileField(blank=True, null=True, upload_to='karar_raporlari/', verbose_name='Karar Raporu')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Başvuru Sonuç',
                'verbose_name_plural': 'Başvuru Sonuçları',
            },
        ),
        migrations.CreateModel(
            name='Tablo5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_dosyasi', models.FileField(upload_to='tablo5/', verbose_name='Tablo 5 PDF Dosyası')),
                ('toplam_puan', models.FloatField(verbose_name='Toplam Puan')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tablo 5',
                'verbose_name_plural': 'Tablo 5 Dosyaları',
            },
        ),
    ]
