# Generated by Django 5.1.7 on 2025-04-23 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basvuru', '0001_initial'),
        ('faaliyet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adayfaaliyet',
            name='faaliyet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aday_faaliyetler', to='faaliyet.faaliyet'),
        ),
    ]
