# Generated by Django 5.1.7 on 2025-04-23 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basvuru', '0002_initial'),
        ('ilanlar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='basvuru',
            name='aday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basvurular', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basvuru',
            name='ilan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basvurular', to='ilanlar.ilan'),
        ),
        migrations.AddField(
            model_name='adayfaaliyet',
            name='basvuru',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aday_faaliyetler', to='basvuru.basvuru'),
        ),
        migrations.AddField(
            model_name='basvurusonuc',
            name='basvuru',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sonuc', to='basvuru.basvuru'),
        ),
        migrations.AddField(
            model_name='basvurusonuc',
            name='karar_veren',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdigi_kararlar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tablo5',
            name='basvuru',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tablo5', to='basvuru.basvuru'),
        ),
        migrations.AlterUniqueTogether(
            name='basvuru',
            unique_together={('aday', 'ilan')},
        ),
    ]
