# Generated by Django 5.1.7 on 2025-04-29 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basvuru', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basvuru',
            old_name='diplama_belgeleri',
            new_name='diploma_belgeleri',
        ),
    ]
