# Generated by Django 5.1.7 on 2025-04-27 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basvuru', '0004_rename_diplama_belgeleri_basvuru_diploma_belgeleri'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegerlendirmeBelgesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belge', models.FileField(upload_to='degerlendirme_belgeleri/')),
                ('belge_adi', models.CharField(blank=True, max_length=255)),
                ('yukleme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('basvuru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degerlendirme_belgeleri', to='basvuru.basvuru')),
                ('yukleyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Değerlendirme Belgesi',
                'verbose_name_plural': 'Değerlendirme Belgeleri',
                'ordering': ['-yukleme_tarihi'],
            },
        ),
    ] 