# Generated by Django 5.1.7 on 2025-04-23 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('temel_alan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255, verbose_name='Birim Adı')),
                ('temel_alan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birimler', to='temel_alan.temelalan')),
            ],
            options={
                'verbose_name': 'Birim',
                'verbose_name_plural': 'Birimler',
            },
        ),
    ]
